name: publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build library
        run: pnpm run build

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          access: "public"
          token: ${{ secrets.NPM_TOKEN }}
